---
app_servers:
  hosts:
    aws_app_server:
      ansible_host: 172.31.7.63
      ansible_post: 22
      ansible_ssh_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/app_server_ssh
      ansible_ssh_common_args: "-o ForwardAgent=yes"
web_servers:
  hosts:
    vagrant_web_server:
      ansible_host: 192.168.68.117
      ansible_port: 22
      ansible_ssh_user: vagrant
      ansible_ssh_private_key_file: ~/.ssh/id_vagrant_default
    aws_web_server:
      ansible_host: aws-web-server

